### ISSUE TITLE
Possible name squatting on crates.io?

### ISSUE THREAD

**Issue by mondeja** [BrettDong/polib#2]
Hi.

I just recently worked on a [Rust port (rspolib)](https://crates.io/crates/rspolib) of the Python library [polib](https://github.com/izimobil/polib). Have used the `rspolib` name because this crate is taking the name `polib`. It's not a problem at all for me to keep the name as `rspolib`, as it shares consistency with the name of [the Python bindings](https://pypi.org/project/rspolib/), clearly pointing that is a port.

So I'm opening this issue for:

- Suggesting you to use rspolib as is implementing a full PO and MO manipulation library.
- To request the crate name `polib`.

Is not a big deal, but probably more consistent for the Rust ecosystem.

Thanks for reading this and cheers.

**Comment by BrettDong** [comment]
The features are largely similar so why rebuild another Rust library?
